### ISSUE TITLE
api.positionstack ---> Error 520 

### ISSUE THREAD

**Issue by rdulak** [piotr-kubica/weather-tiny#2]
Great project !!! Revelation !!!
Unfortunately I stopped at the connection with api.positionstack.
I get the response "Error 520 Web server is returning an unknown error".
Is a Free account enough for the module to work.
Even sending a request from the browser I do not get an answer.
I ask for osugestions. Thank you.

**Comment by piotr-kubica** [comment]
> Great project !!! Revelation !!!

Thank you :)

> I get the response "Error 520 Web server is returning an unknown error".

Seems to be a server side problem. You could contact positionstack and ask if your request is valid.

> Is a Free account enough for the module to work.

with free tier should be ok (limit is 25.000 Requests/per day at the time of writing)

Device does request (by default) every 15 mins so 4*24 per day -> this is optimistic estimation, because in case the request fails there will be a retry.

Also I see possible improvement: request during night could be done sparsely (1/hour) and during datetime reduce from 4 to 3 per hour to improve battery life

**Comment by rdulak** [comment]
Is your system working fine at the moment?
To my eye, something is on the server side ...  
"All systems down" :(
https://status.positionstack.com/

**Comment by piotr-kubica** [comment]
Same for me. Issues seems to lie on https://status.positionstack.com/ server therefore I'm closing this issue.
